#!/bin/bash

# Check style and run tests

# We can't check top level files since there is no cross-platform (easy) way to run the style check within the dev container (when windows users are using vscode's dev container and committing from windows.

./node-start.sh st
./components-start.sh st
./backend-start.sh st
